project_name: validator
builds:
- main: ./cmd/validator
  binary: validator
  tags:
  - netgo
  ldflags:
  - -s -w
  - "-extldflags '-static'"
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64

nfpms:
  -
    formats:
      - deb
      - rpm
    maintainer: "someone"

archives:
  - id: windows
    format_overrides:
      - goos: windows
        format: zip

kos:
  - repository: ghcr.io/kranurag78/validator
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    sbom: none
    main: ./cmd/validator
    preserve_import_paths: false
    platforms:
    - linux/amd64
    - linux/arm64